### ISSUE TITLE
TypeError: Cannot destructure property `login` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by Alanwang2015** [c-hive/fresh-bot#15]
hi, thanks your fresh-bot tools, but when I configured it, it reported an error: 
```
TypeError: Cannot destructure property `login` of 'undefined' or 'null'.
```
This is my fresh-bot.yml:
```
name: Bump stale issues


on:
  schedule:
    # Run every minute
    - cron: '* * * * *'
  push:
    branches: [ master ]


jobs:
  fresh-bot:
    runs-on: ubuntu-latest


    steps:
      - name: Bump stale issues
        uses: c-hive/fresh-bot@v1
        with:
          GITHUB_TOKEN: ${{ secrets.FRESH_BOT_TOKEN }} # Needs `repo` scope
```
The `FRESH_BOT_TOKEN`() is set in https://github.com/Alanwang2015/Actions-Fresh-bot , and it's value is copied from global `Personal access token`, what did I wrong?
